class LangAssets:
  RANK_WEIGHT = 1.0

  SCHWA = "@:"

  NULL = '#'

  FINAL = 'F'
  ONSET = 'O'
  NUCLEUS = 'N'
  CODA = 'Cd'

  MERGER = '-'

  FINAL_SPLIT_SMOOTH = 0.9

  CLOSER_UNKNOWN_PHONEME_PEN = 10
  CLOSER_UNKNOWN_GRAPHEME_PEN = 15

  FARTHER_UNKNOWN_PHONEME_PEN = 1
  FARTHER_UNKNOWN_GRAPHEME_PEN = 5

  MAIN_UNKNOWN_PHONEME_PEN = 20
  MAIN_UNKNOWN_GRAPHEME_PEN = 30
