class LangAssets:
  RANK_WEIGHT = 1.0

  SCHWA = "@:"

  CLOSER_UNKNOWN_PHONEME_PEN = 2
  CLOSER_UNKNOWN_GRAPHEME_PEN = 10

  FARTHER_UNKNOWN_PHONEME_PEN = 1
  FARTHER_UNKNOWN_GRAPHEME_PEN = 20

  MAIN_UNKNOWN_PHONEME_PEN = 5
  MAIN_UNKNOWN_GRAPHEME_PEN = 50
